version: '3.8'

services:
  postgres:
    image: postgres:16.1
    container_name: my_postgres_container
    ports:
      - "5432:5432" # HostPort:ContainerPort
    environment:
      POSTGRES_DB: test
      POSTGRES_USER: example
      POSTGRES_PASSWORD: example
    volumes:
      - ./cache:/var/lib/postgresql/data
